server:
  #端口
  port: 8002
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码
    password: 邮箱授权码
    # 发送者邮箱地址
    username: mo115222@163.com
    # 端口
    port: 25

  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: rabbitmq服务器地址
    # 端口
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual


  # redis配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 15
    # 超时时间：2000毫秒
    timeout: 2000ms
    # 密码
    password:
    # 配置lettuce连接池
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 5
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 10
        # 最小空闲连接，默认0
        min-idle: 5

  datasource:
    username: root
    password: root115
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
